version: '3'

services:
  iipsrv:
    build: ./iipimage
    restart: always
    environment:
      - URI_MAP=iiif/images=>IIIF
      - FILESYSTEM_PREFIX=/var/www/images/
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?err}
    volumes:
      - images:/var/www/images/:ro

  auth:
    build: ./auth
    environment:
      - SECRET_KEY=${AUTH_SECRET_KEY:?err}
      - SECURITY_PASSWORD_SALT=${AUTH_PASSWORD_SALT:?err}
      - DB_CONNECTION=${AUTH_DB_CONNECTION:?err}
      - ADMIN_USERID=${AUTH_ADMIN_USERID:?err}
      - ADMIN_PASSWORD=${AUTH_ADMIN_PASSWORD:?err}

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d:ro
      - ./proxy/certs/:/etc/nginx/certs/:ro
      - proxy-html:/usr/share/nginx/html/:ro
      - manifests:/var/www/iiif/manifests/:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL:?err}
      # proxy should be discovered by label but sometimes it doesn't
      #- NGINX_PROXY_CONTAINER=renamer_proxy_1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d/
      - ./proxy/certs/:/etc/nginx/certs/
      - proxy-html:/usr/share/nginx/html/

volumes:
  images:
    driver: local
    driver_opts:
      type: none
      device: "${IMAGE_DIR:?err}"
      o: bind
  manifests:
    driver: local
    driver_opts:
      type: none
      device: "${MANIFEST_DIR:?err}"
      o: bind
  proxy-html:
