version: '3'

services:
  digilib:
    image: robcast/digilib:snapshot
    restart: always
    environment:
      - BASEDIR_LIST=/var/www/images/
      - IIIF_PREFIX=images
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - VIRTUAL_HOST_PROTO=${VIRTUAL_HOST_PROTO:-https}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?err}
      - IIIF_IMAGE_BASE_URL=${VIRTUAL_HOST_PROTO}://${VIRTUAL_HOST}/iiif/images
      - IIIF_MANIFEST_BASE_URL=${VIRTUAL_HOST_PROTO}://${VIRTUAL_HOST}/iiif/manifests
    volumes:
      - images:/var/www/images/:ro

  auth:
    build: ./auth
    restart: always
    environment:
      - SECRET_KEY=${AUTH_SECRET_KEY:?err}
      - SECURITY_PASSWORD_SALT=${AUTH_PASSWORD_SALT:?err}
      - DB_CONNECTION=${AUTH_DB_CONNECTION:?err}
      - ADMIN_USERID=${AUTH_ADMIN_USERID:?err}
      - ADMIN_PASSWORD=${AUTH_ADMIN_PASSWORD:?err}

  gen_json:
    build: ./gen_json
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - VIRTUAL_HOST_PROTO=${VIRTUAL_HOST_PROTO:-https}
    volumes:
      - authfiles:/authfiles/

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d:ro
      - ./proxy/certs/:/etc/nginx/certs/:ro
      - proxy-html:/usr/share/nginx/html/:ro
      - authfiles:/var/www/iiif/authfiles/:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL:?err}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d/
      - ./proxy/certs/:/etc/nginx/certs/
      - proxy-html:/usr/share/nginx/html/

volumes:
  images:
    driver: local
    driver_opts:
      type: none
      device: "${IMAGE_DIR:?err}"
      o: bind
  proxy-html:
  authfiles:
